[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [19]:
import numpy as np

ones=np.ones(2*8)
print(ones)



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [1]:
import numpy as np
output = np.zeros(20)
print(output)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
import numpy as np
random=np.random.rand(3,4)
print(random)

[[0.06407616 0.43151605 0.02047876 0.72287835]
 [0.21911311 0.48149456 0.485919   0.04871499]
 [0.30616849 0.63305097 0.80675295 0.23492582]]


In [14]:
import numpy as np
array=np.array([0,1,2,3,4,5,6,7,8,9])
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
import numpy as np

a=np.ones((3,3),dtype=bool)

print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [18]:
import numpy as np
array=np.array([0,1,2,3,4,5,6,7,8,9,10])
odd=np.where(array%2 != 0)
array[odd]=-1
print(array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


In [27]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
print(array)
newarray=array.reshape(2,5)
print (newarray)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [41]:
import numpy as np
a=np.arange(1,10).reshape(3,3)
b=np.arange(10,19).reshape(3,3)
c=np.dot(a,b)
print (a)
print(b)
print(c)
e=np.sum(c,axis=1)
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[ 270  648 1026]


In [53]:
import numpy as np
one=np.ones(3)
two=one+one
three=one*3
fhalf=np.concatenate(one,two,three)
four=np.arange(1,4)
ans=np.tile(four,3)
final=np.concatenate(fhalf,ans)
print(final)

TypeError: only integer scalar arrays can be converted to a scalar index